stages:
  - pre
  - deploy

audit:
  stage: pre
  image: node:10-alpine
  only:
    refs:
      - /^feature\/.*$/
      - /^hotfix\/.*$/
  script:
    - npm audit
  tags:
    - docker

outdated:
  stage: pre
  image: node:10-alpine
  only:
    refs:
      - /^feature\/.*$/
      - /^hotfix\/.*$/
  script:
    - npm run ncu
  tags:
    - docker

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker-compose up --build -d
  tags:
    - shell
