version: "3"
services:
  shici:
    build: .
    expose:
      - 3000
    restart: always
    labels:
      - traefik.http.routers.shici-app.rule=Host(`shici.xiange.tech`)
      - traefik.http.routers.shici-app.tls=true
      - traefik.http.routers.shici-app.tls.certresolver=le

networks:
  default:
    external:
      name: traefik_default
