version: "3"
services:
  shici:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    expose:
      - 3000
    restart: always
    labels:
      - "traefik.frontend.rule=Host:shici.xiange.tech"
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf
